const pizzaPlacesObject = {
  "Domino's": {
    cuisines: ["italian", "new york", "pizza"],
    pizzaToppings: {
      pepperoni: 2.2,
      mushrooms: 0.7,
      extraCheese: 1.4,
      onions: 0.5,
      sausage: 2.8,
      extraSauce: 0.8,
    },
    numberOfStars: 4.2,
    favorited: true,
    address: "123 Elm Street",
    zipcode: 54321,
    acceptsReservations: true,
  },
  "Little Caesars": {
    cuisines: ["italian", "american", "pizza"],
    pizzaToppings: {
      pepperoni: 1.8,
      greenPeppers: 0.5,
      extraCheese: 1.6,
      mushrooms: 0.4,
      sausage: 2.5,
      extraSauce: 0.7,
    },
    numberOfStars: 3.8,
    favorited: false,
    address: "789 Oak Avenue",
    zipcode: 67890,
    acceptsReservations: false,
  },
  "Pizza Hut": {
    cuisines: ["italian", "american", "pizza"],
    pizzaToppings: {
      pepperoni: 2.0,
      olives: 0.6,
      extraCheese: 1.7,
      bacon: 2.9,
      greenOlives: 0.5,
      extraSauce: 1.1,
    },
    numberOfStars: 4.0,
    favorited: true,
    address: "456 Maple Lane",
    zipcode: 11235,
    acceptsReservations: true,
  },
  "California Pizza Kitchen": {
    cuisines: ["californian", "pizza"],
    pizzaToppings: {
      pepperoni: 1.9,
      bellPeppers: 0.7,
      extraCheese: 1.8,
      onions: 0.5,
      chicken: 3.0,
      extraSauce: 0.9,
    },
    numberOfStars: 4.5,
    favorited: true,
    address: "321 Birch Boulevard",
    zipcode: 98765,
    acceptsReservations: true,
  },
  "Marco's Pizza": {
    cuisines: ["italian", "chicago", "pizza"],
    pizzaToppings: {
      pepperoni: 2.1,
      greenOlives: 0.6,
      extraCheese: 1.5,
      mushrooms: 0.4,
      ham: 2.7,
      extraSauce: 0.8,
    },
    numberOfStars: 3.9,
    favorited: false,
    address: "654 Pine Road",
    zipcode: 12345,
    acceptsReservations: false,
  },
};

module.exports = pizzaPlacesObject;
